theme: jekyll-theme-minimal
title: Youtube RSS Plugin
description: Adds the RSS button back to Youtube.
logo: https://raw.githubusercontent.com/DeGrandis/Youtube-rss-chrome-plugin/master/plugin/icons/icon128.png
